-- MySQL Script generated by MySQL Workbench
-- Sat Aug  1 11:14:53 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema p2p
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `p2p` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `p2p` ;

-- -----------------------------------------------------
-- Table `p2p`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`activity` (
  `activity_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NULL,
  `img` VARCHAR(100) NULL,
  `link` VARCHAR(255) NULL,
  `task` VARCHAR(20) NOT NULL,
  `publihser_date` INT NOT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`activity_id`),
  UNIQUE INDEX `activity_id_UNIQUE` (`activity_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`activity_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`activity_type` (
  `activity_type_id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NOT NULL,
  `activity_type` INT NOT NULL,
  `activity_send_type` INT NOT NULL COMMENT '\'1\': 红包，\'2\': 现金券，\'3\':年化券, 4: \'积分\'',
  `activity_send_value` VARCHAR(45) NOT NULL,
  `vaild_date` INT NOT NULL DEFAULT 0,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `is_delete` SMALLINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`activity_type_id`),
  UNIQUE INDEX `activity_id_UNIQUE` (`activity_type_id` ASC),
  INDEX `activity_id_idx` (`activity_id` ASC),
  CONSTRAINT `activity_id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `p2p`.`activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`activity_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`activity_record` (
  `activity_records_id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `note` VARCHAR(50) NULL,
  `create_time` VARCHAR(45) NOT NULL,
  `is_delete` SMALLINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`activity_records_id`),
  UNIQUE INDEX `idactivity_records_id_UNIQUE` (`activity_records_id` ASC),
  INDEX `FR_MEMBER_ID_idx` (`member_id` ASC),
  INDEX `FR_ACTIVITY_RECORD_ACTIVITY_ID_idx` (`activity_id` ASC),
  CONSTRAINT `FR_ACTIVITY_RECORD_MEMBER_ID`
    FOREIGN KEY (`member_id`)
    REFERENCES `p2p`.`member` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FR_ACTIVITY_RECORD_ACTIVITY_ID`
    FOREIGN KEY (`activity_id`)
    REFERENCES `p2p`.`activity` (`activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `p2p`.`cms_help`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`cms_help` (
  `cms_help_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `type` TINYINT(1) NOT NULL DEFAULT 0:我要理财；1:充值提现；2:平台介绍,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `create_time` DATETIME NOT NULL,
  `update_time` DATETIME NULL,
  `isDelete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`cms_help_id`),
  UNIQUE INDEX `id_UNIQUE` (`cms_help_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`cms_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`cms_media` (
  `cms_media_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `content` TEXT NULL,
  `source_site` VARCHAR(45) NULL,
  `source_link` VARCHAR(200) NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `publisher_date` INT NOT NULL,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`cms_media_id`),
  UNIQUE INDEX `cms_media_id_UNIQUE` (`cms_media_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`cms_partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`cms_partner` (
  `cms_partner_id` INT NOT NULL AUTO_INCREMENT,
  `img_icon` VARCHAR(100) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`cms_partner_id`),
  UNIQUE INDEX `cms_partner_id_UNIQUE` (`cms_partner_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`cms_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`cms_contact` (
  `cms_contact_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NOT NULL,
  `phone` VARCHAR(100) NOT NULL,
  `qq` VARCHAR(45) NOT NULL,
  `weibo` VARCHAR(200) NOT NULL,
  `weixin` VARCHAR(100) NOT NULL,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`cms_contact_id`),
  UNIQUE INDEX `cms_contact_id_UNIQUE` (`cms_contact_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`cms_notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`cms_notice` (
  `cms_notice_id` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT(1) NOT NULL DEFAULT 0: 官方公告； 1:系统公告,
  `img` VARCHAR(100) NULL,
  `title` VARCHAR(100) NOT NULL,
  `content` TEXT NOT NULL,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `publihser_date` INT NOT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`cms_notice_id`),
  UNIQUE INDEX `cms_notice_id_UNIQUE` (`cms_notice_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`cms_recruitment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`cms_recruitment` (
  `cms_recruitment_id` INT NOT NULL AUTO_INCREMENT,
  `type` TINYINT(1) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` VARCHAR(45) NOT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`cms_recruitment_id`),
  UNIQUE INDEX `cms_recruitment_id_UNIQUE` (`cms_recruitment_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `p2p`.`cms_about`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`cms_about` (
  `cms_about_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `content` TEXT NOT NULL,
  `img` VARCHAR(100) NULL,
  `type` TINYINT(1) NOT NULL,
  `create_time` INT NOT NULL,
  `update_time` INT NULL,
  `create_by` VARCHAR(45) NOT NULL,
  `update_by` VARCHAR(45) NULL,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`cms_about_id`),
  UNIQUE INDEX `cms_about_UNIQUE` (`cms_about_id` ASC))
ENGINE = InnoDB;

USE `p2p` ;

-- -----------------------------------------------------
-- Placeholder table for view `p2p`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `p2p`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `p2p`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `p2p`.`view1`;
USE `p2p`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
