<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Are you sure you want to delete this item?' => '',
    'Attribute' => '',
    'Auth Key' => '',
    'Bind Email Account' => '',
    'Email Verify Token' => '',
    'Is Auto Into' => '',
    'Is Delete' => '',
    'Is Deleted' => '',
    'Link ID' => '',
    'Member Bank ID' => '',
    'Member Coupon ID' => '',
    'Member ID' => '',
    'Member Statistic ID' => '',
    'Member Status ID' => '',
    'Note' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Result' => '',
    'Statistic Change Record ID' => '',
    'wrong id card number' => '',
    'Account Money' => '账户金额',
    'Bank Name' => '银行名称',
    'Bank User Name' => '银行开户姓名',
    'Bonus' => '红包',
    'Branch Name' => '开户银行分行名称',
    'Card No' => '银行卡号',
    'City' => '城市',
    'Collect Interest' => '待回款利息',
    'Collect Principal' => '待回款本金',
    'Create' => '新建',
    'Create Member' => '新建用户',
    'Create Time' => '新建时间',
    'Delete' => '删除',
    'Email' => '邮箱',
    'Email Status' => '是否邮箱认证',
    'Empirical Value' => '经验值',
    'Expire Date' => '到期时间',
    'Freezon Money' => '冻结金额',
    'Id Card' => '身份账号',
    'Id Card Status' => '是否实名认证',
    'Is First Invest' => '是否为新手投资',
    'Member' => '用户',
    'Member Manage' => '用户管理',
    'Members' => '用户',
    'Mobile' => '手机号',
    'Mobile Status' => '是否手机认证',
    'Package Earning' => '钱包收益',
    'Package Money' => '钱包金额',
    'Points' => '积分',
    'Project Earning' => '投资收益',
    'Project Total Money' => '投资金额',
    'Province' => '省份',
    'Real Name' => '真实姓名',
    'Recommend Type' => '推荐方式',
    'Recommend User' => '推荐人',
    'Reset' => '重置',
    'Search' => '搜索',
    'Status' => '状态',
    'Type' => '类型',
    'Update' => '更新',
    'Update Time' => '更新时间',
    'Update {modelClass}: ' => '更新{modelClass}: ',
    'Used Bonus' => '已使用红包',
    'Used Time' => '使用时间',
    'User Name' => '用户名',
    'Value' => '值',
];
