<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Notification Template ID' => 'ID',
    'Signup' => '注册成功',
    'Active' => '是否启用',
    'Create' => '新建',
    'Create Notification Template' => '新建通知内容',
    'Delete' => '删除',
    'Email' => '邮件',
    'Event' => '通知类型',
    'Events' => '通知类型',
    'Message' => '系统通知',
    'Notification Templates' => '通知内容',
    'Notification type' => '通知方式',
    'Receiver' => '接收人',
    'Reset' => '重置',
    'Search' => '搜索',
    'Sms' => '短信',
    'Template' => '内容',
    'Title' => '标题',
    'Type' => '通知方式',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass}: ',
    'notification' => '通知',
];
