<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Address' => '',
    'Are you sure you want to delete this item?' => '',
    'Cms' => '',
    'Cms About ID' => '',
    'Cms Abouts' => '',
    'Cms Contact ID' => '',
    'Cms Contacts' => '',
    'Cms Help ID' => '',
    'Cms Helps' => '',
    'Cms Media' => '',
    'Cms Media ID' => '',
    'Cms Notice ID' => '',
    'Cms Notices' => '',
    'Contact' => '',
    'Content' => '',
    'Create' => '',
    'Create By' => '',
    'Create Cms About' => '',
    'Create Cms Contact' => '',
    'Create Cms Help' => '',
    'Create Cms Media' => '',
    'Create Cms Notice' => '',
    'Create Time' => '',
    'Delete' => '',
    'Help' => '',
    'Img' => '',
    'Is Delete' => '',
    'Media' => '',
    'Notice' => '',
    'Phone' => '',
    'Publihser Date' => '',
    'Publisher Date' => '',
    'Qq' => '',
    'Reset' => '',
    'Search' => '',
    'Source Link' => '',
    'Source Site' => '',
    'Title' => '',
    'Type' => '',
    'Update' => '',
    'Update By' => '',
    'Update Time' => '',
    'Update {modelClass}: ' => '',
    'Weibo' => '',
    'Weixin' => '',
    'Article' => '@@@@',
    'Article ID' => '@@@@',
    'Articles' => '@@@@',
    'Block' => '@@@@',
    'Block ID' => '@@@@',
    'Blocks' => '@@@@',
    'Categories' => '@@@@',
    'Category' => '@@@@',
    'Category ID' => '@@@@',
    'Comment ID' => '@@@@',
    'Create Article' => '@@@@',
    'Create Block' => '@@@@',
    'Create Page' => '@@@@',
    'Created At' => '@@@@',
    'Created By' => '@@@@',
    'Key' => '@@@@',
    'Layout' => '@@@@',
    'Link ID' => '@@@@',
    'Page' => '@@@@',
    'Page ID' => '@@@@',
    'Pages' => '@@@@',
    'Parent ID' => '@@@@',
    'Post ID' => '@@@@',
    'Updated At' => '@@@@',
    'Updated By' => '@@@@',
];
