<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Account Money' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Bank Name' => '',
    'Bank User Name' => '',
    'Bonus' => '',
    'Branch Name' => '',
    'Card No' => '',
    'City' => '',
    'Collect Interest' => '',
    'Collect Principal' => '',
    'Create' => '',
    'Create Member' => '',
    'Create Time' => '',
    'Delete' => '',
    'Email' => '',
    'Email Status' => '',
    'Email Verify Token' => '',
    'Empirical Value' => '',
    'Expire Date' => '',
    'Freezon Money' => '',
    'Id Card' => '',
    'Id Card Status' => '',
    'Is Delete' => '',
    'Is Deleted' => '',
    'Is First Invest' => '',
    'Member' => '',
    'Member Bank ID' => '',
    'Member Coupon ID' => '',
    'Member ID' => '',
    'Member Statistic ID' => '',
    'Member Status ID' => '',
    'Members' => '',
    'Mobile' => '',
    'Mobile Status' => '',
    'Package Earning' => '',
    'Package Money' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Points' => '',
    'Project Earning' => '',
    'Project Total Money' => '',
    'Province' => '',
    'Real Name' => '',
    'Recomend Type' => '',
    'Recomend User' => '',
    'Reset' => '',
    'Search' => '',
    'Status' => '',
    'Type' => '',
    'Update' => '',
    'Update Time' => '',
    'Update {modelClass}: ' => '',
    'Used Bonus' => '',
    'Used Time' => '',
    'User Name' => '',
    'Value' => '',
];
