<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '有效',
    'Add {type} Value' => '添加{type}值',
    'Are you sure you want to delete this item?' => '',
    'Boolean' => '是否',
    'Create' => '新建',
    'Create Url Rewrite' => '新建网址重写',
    'Data List ID' => '',
    'Data Lists' => '下拉列表',
    'DataList' => '下拉列表',
    'Delete' => '删除',
    'Disable' => '禁用',
    'Edit' => '编辑',
    'Enable' => '启用',
    'Home' => '首页',
    'Is Active' => '是否有效',
    'Is Removed' => '是否移除',
    'Key' => '键',
    'List' => '列表',
    'Menus' => '菜单',
    'No' => '否',
    'Off' => '关',
    'On' => '开',
    'Params' => '参数',
    'Request Path' => '请求路径',
    'Reset' => '重置',
    'Route' => '路由',
    'Save' => '保存',
    'Search' => '搜索',
    'Setting' => '配置',
    'Setting ID' => '',
    'System' => '系统',
    'Type' => '类型',
    'Update' => '更新',
    'Update Menu' => '更新菜单',
    'Update {modelClass}: ' => '更新{modelClass}: ',
    'Update {type} Value: ' => '更新{type}值: ',
    'Url' => '网址',
    'Url Rewrite' => '网址重写',
    'Url Rewrite ID' => '',
    'Url Rewrites' => '网址重写',
    'UrlRewrite' => '网址重写',
    'Value' => '值',
    'Yes' => '是',
    'main config' => '',
    'site config' => '',
    'site description' => '',
    'site description for seo' => '',
    'site keywords' => '',
    'site keywords for seo' => '',
    'site title' => '',
    'site title show in browser at home page, if the code not set' => '',
];
