<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cms' => '',
    'Cms About ID' => '',
    'Cms Contact ID' => '',
    'Cms Help ID' => '',
    'Cms Law ID' => '',
    'Cms Laws' => '法律保障',
    'Cms Media' => '',
    'Cms Media ID' => '',
    'Cms Notice ID' => '',
    'Cms Notices' => '',
    'Cms Recruitment ID' => '',
    'Cms Recruitments' => '诚聘英才',
    'Create Cms Law' => '创建法律保障',
    'Create Cms Recruitment' => '创建招聘',
    'Is Delete' => '',
    'Law' => '法律保障',
    'Publihser Date' => '',
    'Publisher Date' => '',
    'Recruitment' => '诚聘英才',
    'Reset' => '',
    'Search' => '',
    'Source Link' => '',
    'Source Site' => '',
    'Article' => '@@@@',
    'Article ID' => '@@@@',
    'Articles' => '@@@@',
    'Block' => '@@@@',
    'Block ID' => '@@@@',
    'Blocks' => '@@@@',
    'Categories' => '@@@@',
    'Category' => '@@@@',
    'Category ID' => '@@@@',
    'Comment ID' => '@@@@',
    'Create Article' => '@@@@',
    'Create Block' => '@@@@',
    'Create Page' => '@@@@',
    'Created At' => '@@@@',
    'Created By' => '@@@@',
    'Key' => '@@@@',
    'Layout' => '@@@@',
    'Link ID' => '@@@@',
    'Page' => '@@@@',
    'Page ID' => '@@@@',
    'Pages' => '@@@@',
    'Parent ID' => '@@@@',
    'Post ID' => '@@@@',
    'Updated At' => '@@@@',
    'Updated By' => '@@@@',
    'About' => '关于我们',
    'Address' => '地址',
    'Are you sure you want to delete this item?' => '你确定要删除这个项目吗',
    'Cms Abouts' => '关于我们',
    'Cms Contacts' => '联系我们',
    'Cms Helps' => '帮助',
    'Contact' => '联系我们',
    'Content' => '内容',
    'Create' => '创建',
    'Create By' => '创建人',
    'Create Cms About' => '创建单页',
    'Create Cms Contact' => '创建单页',
    'Create Cms Help' => '创建单页',
    'Create Cms Media' => '创建单页',
    'Create Cms Notice' => '创建单页',
    'Create Time' => '创建时间',
    'Delete' => '删除',
    'Help' => '帮助',
    'Img' => '图片',
    'Media' => '媒体报道',
    'Notice' => '官方公告',
    'Phone' => '手机',
    'Qq' => 'qq',
    'Title' => '标题',
    'Type' => '类型',
    'Update' => '更新',
    'Update By' => '更新人',
    'Update Time' => '更新时间',
    'Update {modelClass}: ' => '更新',
    'Weibo' => '微博',
    'Weixin' => '微信',
];
