<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administrator' => '管理员',
    'Administrator List' => '管理员列表',
    'Auth' => '权限管理',
    'Create' => '新建',
    'Create {modelClass}' => '新建{modelClass}',
    'Created At' => '创建时间',
    'Data' => '日期',
    'Delete' => '删除',
    'Description' => '描述',
    'Disabled' => '禁用',
    'Edit' => '编辑',
    'Enabled' => '启用',
    'List' => '列表',
    'Name' => '名字',
    'Password' => '密码',
    'Permission List' => '权限列表',
    'Role' => '角色',
    'Role List' => '角色列表',
    'Role Name' => '角色名',
    'Roles' => '角色',
    'Rule Name' => '规则名',
    'Select All' => '全选',
    'Type' => '类型',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新{modelClass}: ',
    'Updated At' => '更新时间',
    'User' => '用户',
];
