<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'AutoRecord' => '自动审核记录',
    'Create' => '',
    'Create Withdraw Record' => '',
    'Delete' => '',
    'Deposit Record ID' => '',
    'Deposit Type' => '',
    'FailRecord' => '未通过记录',
    'FirstRecord' => '第一次审核记录',
    'Is Delete' => '',
    'PendingRecord' => '等待审核',
    'Reset' => '',
    'Search' => '',
    'SuccessRecord' => '审核通过记录',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Verify Date' => '@@@@',
    'Verify User' => '@@@@',
    'Counter Fee' => '提现手续费',
    'Create Time' => '创建时间',
    'First Verify Date' => '第一次审核日期',
    'First Verify User' => '第一次审核用户',
    'Member ID' => '用户',
    'Money' => '提现金额',
    'Second Verify Date' => '第二次审核日期',
    'Second Verify User' => '第二次审核用户',
    'Status' => '状态',
    'Update Time' => '更新时间',
    'Withdraw Records' => '提现记录',
    'WithdrawRecord' => '提现记录',
];
