<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Deposit Record ID' => '',
    'Is Delete' => '',
    'Withdraw' => '',
    'AutoRecord' => '@@自动审核记录@@',
    'Verify Date' => '@@@@',
    'Verify User' => '@@@@',
    'Are you sure you want to delete this item?' => '您是否确定要删除这条记录？',
    'Auto Withdraw' => '自动提现',
    'Can Withdraw Money' => '可提现金额',
    'Counter Fee' => '提现手续费',
    'Create' => '创建',
    'Create Time' => '创建时间',
    'Create Withdraw Record' => '创建提现记录',
    'Delete' => '删除',
    'Deposit Type' => '提现类型',
    'FailRecord' => '未通过记录',
    'First Verify Date' => '第一次审核日期',
    'First Verify Memo' => '第一次审核备注',
    'First Verify User' => '第一次审核用户',
    'FirstRecord' => '第一次审核记录',
    'Manual Withdraw' => '手动提现',
    'Member ID' => '用户',
    'Money' => '提现金额',
    'PendingRecord' => '等待审核',
    'Reset' => '重置',
    'Search' => '搜索',
    'Second Verify Date' => '第二次审核日期',
    'Second Verify Memo' => '第二次审核备注',
    'Second Verify User' => '第二次审核用户',
    'Status' => '状态',
    'SuccessRecord' => '审核通过记录',
    'Update' => '更新',
    'Update Time' => '更新时间',
    'Update {modelClass}: ' => '更新提现记录',
    'Withdraw Fail' => '提现失败',
    'Withdraw Fee' => '提现费用',
    'Withdraw First Verify Success' => '提现第一次审核成功',
    'Withdraw Money' => '提现金额',
    'Withdraw Pending' => '提现待审核',
    'Withdraw Records' => '提现记录',
    'Withdraw Success' => '提现成功',
    'WithdrawRecord' => '提现记录',
];
