<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity ID' => '',
    'Activity Records' => '',
    'Activity Records ID' => '',
    'AnnualRecord' => '',
    'Are you sure you want to delete this item?' => '',
    'BonusRecord' => '',
    'CashRecord' => '',
    'Coupon Annual Record ID' => '',
    'Coupon Annual Records' => '',
    'Coupon Bonus Record ID' => '',
    'Coupon Bonus Records' => '',
    'Coupon Cash Record ID' => '',
    'Coupon Cash Records' => '',
    'Create Activity Record' => '',
    'Create Activity Records' => '',
    'Create Coupon Annual Record' => '',
    'Create Coupon Annual Records' => '',
    'Create Coupon Bonus Record' => '',
    'Create Coupon Bonus Records' => '',
    'Create Coupon Cash Record' => '',
    'Create Coupon Cash Records' => '',
    'Create Exchange Record' => '',
    'Create Exchange Records' => '',
    'Discount Money' => '',
    'Empiric Value' => '',
    'Exchange Records' => '',
    'Exchange Records ID' => '',
    'ExchangeRecord' => '',
    'Interst Money' => '',
    'Is Delete' => '',
    'Member Coupon ID' => '',
    'Member ID' => '',
    'Member Sign Record ID' => '',
    'Note' => '',
    'Product Map ID' => '',
    'Project ID' => '',
    'Project Invest ID' => '',
    'Project Invest Point Record' => '',
    'Rate' => '',
    'Reset' => '',
    'Search' => '',
    'Target Date' => '',
    'exchange success' => '',
    'Activities' => '活动',
    'Activity' => '活动',
    'Activity Send Type' => '活动券类型',
    'Activity Send Value' => '值',
    'Activity Type' => '任务类型',
    'Annual' => '年化券',
    'App' => '登录app',
    'Bind Email' => '绑定邮箱',
    'Bind Phone' => '绑定手机',
    'Bonus' => '红包',
    'Cash' => '现金券',
    'Coupon Annual' => '年化券',
    'Coupon Bonus' => '红包',
    'Coupon Cash' => '现金券',
    'Create' => '创建',
    'Create Activity' => '创建任务',
    'Create Product' => '创建活动券',
    'Create Product Map' => '创建活动券',
    'Create Time' => '创建时间',
    'Delete' => '删除',
    'Duration' => '有效期',
    'Exchange Points' => '交换积分',
    'Exchange Value' => '交换值',
    'Invest' => '投资',
    'Points' => '积分',
    'Ponit' => '积分',
    'Product' => '活动券',
    'Product Maps' => '活动券',
    'Recharge' => '充值',
    'Share' => '分享',
    'Subscribe' => '订阅微信公众号',
    'Type' => '类型',
    'Update' => '更新',
    'Update Time' => '更新时间',
    'Update {modelClass}: ' => '更新',
    'Vaild Date' => '有效期',
];
