<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '您确定要删除这条记录吗？',
    'Counter Fee' => '手续费',
    'Create' => '创建',
    'Create Project Invest Transfer Apply' => '创建债券转让项目',
    'Create Time' => '创建时间',
    'Delete' => '删除',
    'Discount Money' => '优惠金额',
    'Discount Rate' => '优惠比例',
    'Failed Check' => '审核失败',
    'Is Delete' => '是否删除',
    'Member ID' => '用户',
    'Min Money' => '最小金额',
    'Passed Check' => '审核通过',
    'Pending Check' => '待审核',
    'Project ID' => '',
    'Project Invest ID' => '',
    'Project Invest Transfer Applies' => '债券转让项目',
    'Project Invest Transfer Apply ID' => '',
    'Project Transfer Discount Record ID' => '',
    'Rate' => '年利率',
    'Repayment' => '还款',
    'Reset' => '重置',
    'Search' => '搜索',
    'Status' => '状态',
    'Total Invest Money' => '总投资金额',
    'Transfer' => '债券转让',
    'Transfer End' => '项目结束',
    'Transfer Money' => '转让金额',
    'Transfering' => '转让中',
    'Update' => '更新',
    'Update Time' => '更新时间',
    'Update {modelClass}: ' => '更新债券转让项目',
    'Verify Date' => '验证时间',
    'Verify User' => '验证者',
];
