<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity' => '活动',
    'Activity ID' => '',
    'Activity Records ID' => '',
    'Activity Send Type' => '',
    'Activity Send Value' => '',
    'Activity Type' => '',
    'Are you sure you want to delete this item?' => '',
    'Coupon Annual' => '年化券',
    'Coupon Annual Record ID' => '',
    'Coupon Bonus' => '红包',
    'Coupon Bonus Record ID' => '',
    'Coupon Cash' => '现金券',
    'Coupon Cash Record ID' => '',
    'Create' => '创建',
    'Create Product' => '创建活动券',
    'Create Product Map' => '创建活动券',
    'Create Time' => '创建时间',
    'Delete' => '删除',
    'Discount Money' => '',
    'Duration' => '有效期',
    'Empiric Value' => '',
    'Exchange Points' => '交换积分',
    'Exchange Records ID' => '',
    'Exchange Value' => '交换值',
    'Interst Money' => '',
    'Is Delete' => '',
    'Member Coupon ID' => '',
    'Member ID' => '',
    'Member Sign Record ID' => '',
    'Note' => '',
    'Ponit' => '',
    'Product' => '活动券',
    'Product Map ID' => '',
    'Product Maps' => '活动券',
    'Project ID' => '',
    'Project Invest ID' => '',
    'Project Invest Point Record' => '',
    'Rate' => '',
    'Target Date' => '',
    'Type' => '类型',
    'Update' => '更新',
    'Update Time' => '更新时间',
    'Update {modelClass}: ' => '更新',
    'Vaild Date' => '',
];
