<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Into Package' => '',
    'Is Delete' => '',
    'Member ID' => '',
    'Out Package' => '',
    'P2P config' => '',
    'Package Interest Record ID' => '',
    'Package Rate' => '',
    'Package Record ID' => '',
    'Package config' => '',
    'Reset' => '',
    'Search' => '',
    'the package rate, 7 means 7%' => '',
    'Package Into' => '@@钱包转出@@',
    'Package Out' => '@@钱包转入@@',
    'Create Time' => '创建时间',
    'Daily Interest' => '每日收益',
    'Exchange Cash' => '变动金额',
    'Into money' => '转出金额',
    'Into package money must be int' => '转出金额必须为整数',
    'Into package money must more than zero' => '转出金额必须为大于零',
    'Into package money must no more than account money' => '账户余额不足',
    'Out Money' => '转入金额',
    'Out package money must be int' => '转入金额必须为整数',
    'Out package money must more than zero' => '转入金额必须为大于零',
    'Out package money must no more than package money' => '钱包余额不足',
    'Package' => '钱包管理',
    'Package Interest Record' => '钱包收益记录',
    'Package Interest Records' => '钱包收益记录',
    'Package Into Records' => '钱包转出记录',
    'Package Out Records' => '钱包转入记录',
    'Target Date' => '收益日期',
    'Type' => '类型',
];
