<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create Time' => '',
    'Daily Interest' => '',
    'Exchange Cash' => '',
    'Into money' => '',
    'Into package money must be int' => '',
    'Into package money must more than zero' => '',
    'Into package money must no more than account money' => '',
    'Is Delete' => '',
    'Member ID' => '',
    'Out Money' => '',
    'Out money' => '',
    'Out package money must be int' => '',
    'Out package money must more than zero' => '',
    'Out package money must no more than package money' => '',
    'Package Interest Record ID' => '',
    'Package Record ID' => '',
    'Target Date' => '',
    'Type' => '',
];
