<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create' => '',
    'Create Recharge Record' => '',
    'Delete' => '',
    'Is Delete' => '',
    'Recharge' => '',
    'Recharge Record ID' => '',
    'Reset' => '',
    'Search' => '',
    'Status' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Use For ID' => '',
    'Use For Type' => '',
    'Error recharge method' => '@@@@',
    'Project Invest ID' => '@@@@',
    'Use For' => '@@@@',
    'CapitalManagement' => '资金管理',
    'Create Time' => '创建时间',
    'Member ID' => '用户',
    'Money' => '金额',
    'Recharge Records' => '充值记录',
    'Recharge Type' => '充值方式',
    'Recharge method' => '充值方式',
    'Recharge money' => '充值金额',
    'RechargeRecord' => '充值记录',
    'Transaction ID' => '交易号',
    'Update Time' => '更新时间',
];
